[agent]
  interval = "10s"
  collection_jitter = "2s"
  flush_interval = "55s"
  flush_jitter = "5s"

[[inputs.mem]]
[[inputs.swap]]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.processes]]
[[inputs.netstat]]
[[inputs.cpu]]
  percpu = false
  totalcpu = true
[[inputs.disk]]
  mount_points = ["/", "/data"]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.system]]
  fielddrop = ["uptime_format"]
[[inputs.net]]
  ignore_protocol_stats = true

[[inputs.mysql]]
  servers = ["root:MYSQL_DSN@tcp(127.0.0.1:3306)/?tls=false"]
  metric_version = 2
  gather_global_variables = true
  interval_slow = "10m"
  
[[inputs.fail2ban]]

[[aggregators.merge]]
  drop_original = true

[[outputs.amqp]]
  brokers = ["amqp://AMQP_DSN/telegraf"]
  max_messages = 10
  exchange = "telegraf2"
  exchange_type = "topic"
  exchange_durability = "durable"
  username = "telegraf"
  password = "AMQP_PWD"
  auth_method = "PLAIN"
  routing_key = "telegraf2"
  delivery_mode = "transient"
